// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgl2L1ZYcOcRYyhyNWsdrFT3MdXElPWnI',
    appId: '1:135356959595:web:1854827d8c4e9acb2f1a2e',
    messagingSenderId: '135356959595',
    projectId: 'wasemap-ef30a',
    authDomain: 'wasemap-ef30a.firebaseapp.com',
    storageBucket: 'wasemap-ef30a.firebasestorage.app',
    measurementId: 'G-4LB5MNHRTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsdCfiShr64gnqdEfotPMCuDzVP0sMo0',
    appId: '1:135356959595:android:5709fb0a0f540e332f1a2e',
    messagingSenderId: '135356959595',
    projectId: 'wasemap-ef30a',
    storageBucket: 'wasemap-ef30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqcTPRRoWB3Tqek-u4wgyDU2TxPS6hs4M',
    appId: '1:135356959595:ios:0d3fa9449533bead2f1a2e',
    messagingSenderId: '135356959595',
    projectId: 'wasemap-ef30a',
    storageBucket: 'wasemap-ef30a.firebasestorage.app',
    iosBundleId: 'com.example.waseMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqcTPRRoWB3Tqek-u4wgyDU2TxPS6hs4M',
    appId: '1:135356959595:ios:0d3fa9449533bead2f1a2e',
    messagingSenderId: '135356959595',
    projectId: 'wasemap-ef30a',
    storageBucket: 'wasemap-ef30a.firebasestorage.app',
    iosBundleId: 'com.example.waseMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgl2L1ZYcOcRYyhyNWsdrFT3MdXElPWnI',
    appId: '1:135356959595:web:525d97b0ba04c6192f1a2e',
    messagingSenderId: '135356959595',
    projectId: 'wasemap-ef30a',
    authDomain: 'wasemap-ef30a.firebaseapp.com',
    storageBucket: 'wasemap-ef30a.firebasestorage.app',
    measurementId: 'G-PELG9SN5HZ',
  );
}
